version: '2'

services:
  proxy:
    env_file: .env
    build: politips_proxy/
    links:
      - api:api
    volumes:
      - ./politips_proxy/:/home/politips/politips/politips_proxy/
    ports:
      - 8000:8000

  db:
    env_file: .env
    image: postgres
    volumes:
      - data:/var/lib/postgresql/data/

  api:
    env_file: .env
    build: politips_api/
    command: uwsgi --ini uwsgi.ini
    volumes:
      - ./politips_api/:/home/politips/politips/politips_api/
    links:
      - db:db

  frontend:
    env_file: .env
    build: politips-frontend/
    volumes:
      - ./politips-frontend/:/home/politips/politips/politips-frontend/
      - /home/politips/politips/politips-frontend/node_modules

volumes:
  data: {}
