# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-05 18:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('politips_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legislatorship',
            name='legislator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legislatorships', to='politips_api.Legislator'),
        ),
        migrations.AlterField(
            model_name='legislatorship',
            name='legislature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legislatorships', to='politips_api.Legislature'),
        ),
    ]
