# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-05 19:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('politips_api', '0004_auto_20160805_1950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='name',
            new_name='decision',
        ),
        migrations.AddField(
            model_name='agendaitem',
            name='item_number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='agendaitem',
            name='agenda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda_items', to='politips_api.Agenda'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='agenda_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='politips_api.AgendaItem'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='legislatorship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='politips_api.Legislatorship'),
        ),
    ]
