# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-05 23:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politips', '0005_auto_20160805_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='decision',
            field=models.CharField(choices=[['Yea', 'Yea'], ['Nay', 'Nay'], ['Abstain', 'Abstain'], ['Off dais', 'Off dais']], max_length=255),
        ),
    ]
